# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95b1b1f66829c845e7dbba121ab796dbf3e0373cfe38be6a0d50df6876ba9dfdb5be08d9311de12afd5c75f0ea1f0c8a62e3c39043c30b0bf6ece4c1f6df77b0

test:
  secret_key_base: ab3cab45ca79747aef2c140e09882f493da5d38d697b4e34141c797310687f1999e0c88e837716f727397121fd2b1ed12ea71eb856a1e7bb2ec825fd717a65e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
